apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring_boot_app
spec:
  selector:
    matchLabels:
      app: spring_boot_app
  template:
    metadata:
      labels:
        app: spring_boot_app
    spec:
      containers:
      - name: spring_boot_app
        image: k0m0l/bootapp:bootapp
        ports : 
         - containerPort: 8085
        env : 
         - name : PORT
           value : "8085"
---
apiVersion: v1
kind: Service
metadata:
  name: spring_boot_app
spec:
  type : NodePort
  selector:
    app: spring_boot_app
  ports:
  - port: 90
    targetPort: 8085
    