apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
spec:
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot
        image: k0m0l/bootapp:bootapp
        ports : 
         - containerPort: 8085
        env : 
         - name : PORT
           value : "8085"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot
  type : NodePort
  ports:
  - protocol : TCP
    port: 8085
    targetPort: 8085
    nodePort : 30000
